name: Generate ASCII art

on: push

jobs:
  cowsay:
    runs-on: ubuntu-latest
    steps:
      - name: checkout branch
        uses: actions/checkout@v4
      - name: install cowsay
        run: sudo apt-get install cowsay -y
      - name: Execute cowsay cmd
        run: cowsay -f dragon "RUNNNNNN!!!! NIGERRROOOOOO (in japanese)" >> dragon.txt
      - name: Test File exists
        run: grep -i "run" dragon.txt
      - name: Read file
        run: cat dragon.txt
      - name: Checkout Repo files
        run: ls -ltra
