name: Generate ASCII art

on: push

jobs:
  cowsay:
    runs-on: ubuntu-latest
    steps:
      - name: checkout branch
        uses: actions/checkout@v4
      - name: Checkout Repo files
        run: ls -ltra
      - name: Executing Shell Script
        run: |
          chmod +x ascii-script.sh
          ./ascii-script.sh
